apiVersion: v2
name: custom
description: A Helm chart for deploying a generic Docker image with optional PostgreSQL database
type: application
version: 0.4.10
appVersion: "latest"
keywords:
  - custom
  - docker
  - postgres
  - generic
maintainers:
  - name: FeLiNa22

dependencies:
  - name: postgres
    version: ">=1.0.0"
    repository: "file://../postgres"
    alias: postgres
    condition: postgres.enabled
