{{- if and .Values.homeassistant.enabled .Values.homeassistant.postgres.password }}
{{- $postgresHost := printf "%s-postgres" .Release.Name -}}
{{- if eq .Values.homeassistant.postgres.mode "cluster" -}}
{{- $postgresHost = printf "%s-postgres-cluster-rw" .Release.Name -}}
{{- else if eq .Values.homeassistant.postgres.mode "external" -}}
{{- $postgresHost = printf "%s:%v" .Values.homeassistant.postgres.external.host (.Values.homeassistant.postgres.external.port | default 5432) -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ha-secrets
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
stringData:
  secrets.yaml: |
    recorder_db_url: "postgresql://{{ .Values.homeassistant.postgres.username }}:{{ .Values.homeassistant.postgres.password }}@{{ $postgresHost }}/{{ .Values.homeassistant.postgres.database }}"
{{- end }}
