name: home-assistant
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: "2026.3.3"
version: 1.2.7
description: Home Assistant Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/home-assistant
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - home-assistant
  - smart-home
  - automation
sources:
  - https://github.com/home-assistant/core
  - https://github.com/pajikos/home-assistant-helm-chart

dependencies:
  - name: home-assistant
    version: "0.3.50"
    repository: "https://pajikos.github.io/home-assistant-helm-chart/"
    alias: homeassistant
    condition: homeassistant.enabled
